name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: npm test
      
    - name: Check version consistency
      run: npm run version:check
      
    - name: Run build
      run: npm run build:full

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build:full
      
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          Release ${{ steps.version.outputs.VERSION }}
          
          ## Changes
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details.
          
          ## Installation
          ```bash
          npm install remark-wiki-link-a@${{ steps.version.outputs.VERSION }}
          ```
          
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create package artifact
      run: npm pack
      
    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: npm-package-${{ steps.version.outputs.VERSION }}
        path: remark-wiki-link-a-*.tgz
        retention-days: 30